### ISSUE TITLE
line numbers and copying adds additional new-lines in-between

### ISSUE THREAD

**Issue by GeopJr** [ralsina/tartrazine#17]
Something I noticed when using the line_numbers option is that when copying the code, it adds an additional new line between lines:
e.g. when copying the following
```Makefile
windows:
#	reset folder
	rm -rf "collision_windows"
	mkdir -p "collision_windows/bin"
	mkdir -p "collision_windows/share/applications"
	mkdir -p "collision_windows/share/glib-2.0/schemas"
	mkdir -p "collision_windows/share/icons"
	mkdir -p "collision_windows/share/locale"
```

It gets copied as
```Makefile
windows:

#	reset folder

	rm -rf "collision_windows"

	mkdir -p "collision_windows/bin"

	mkdir -p "collision_windows/share/applications"

	mkdir -p "collision_windows/share/glib-2.0/schemas"

	mkdir -p "collision_windows/share/icons"

	mkdir -p "collision_windows/share/locale"
```

after further investigation, I found out it's caused by the line numbers having `user-select:none`.

From my side, I overrode `line_label` to remove the style and text (plus the IDs but that's just preference):

```crystal
class Tartrazine::Html < Tartrazine::Formatter
  def line_label(i : Int32) : String
    line_class = highlighted?(i + 1) ? " #{get_css_class("LineHighlight")}" : ""
    "<span class=\"line-no#{line_class}\"></span>"
  end
end
```

and then used [CSS counters](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_counter_styles/Using_CSS_counters) 

```css
.blog-post > div pre {
    counter-reset: line;
}

.blog-post > div pre > code span.line-no {
    counter-increment: line;
}

.blog-post > div pre > code .line-no:before{
    content: counter(line);
    display: inline-block;
    text-align: right;
    width: 3rem;
    margin-right: 1rem;
}
```

| before | after |
| --- | ---|
|  ![Image](https://github.com/user-attachments/assets/4558b22f-ccd0-4859-8ffc-ff5b9003e229) | ![Image](https://github.com/user-attachments/assets/b2abec7c-f730-4302-8f0f-d0b00fe964b8) |

Style is similar but the main difference is that there's no new-lines between lines when copying.

---

I don't know how viable it would be to fix this from tartrazine's side, especially since the pseudo classes can't be used in inline-styles, maybe an in-body `<style>` above `<pre>`? Anyway, just thought I should bring it to your attention :)
